### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by ranehal** [j-unayed/FTPaddict#1]
![image](https://github.com/user-attachments/assets/a29c83af-655b-48d3-8b38-dc433e2ac263)

**Comment by j-unayed** [comment]
> ![image](https://private-user-images.githubusercontent.com/37912802/371870052-a29c83af-655b-48d3-8b38-dc433e2ac263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MzAyNTQsIm5iZiI6MTcyNzYyOTk1NCwicGF0aCI6Ii8zNzkxMjgwMi8zNzE4NzAwNTItYTI5YzgzYWYtNjU1Yi00OGQzLThiMzgtZGM0MzNlMmFjMjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDE3MTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlN2Q1YzU1YTU0YTA4YTU1ZWY0YjAwMDc4NWY5ZmExM2UxM2Y4YjlhNGQ4ZWI5ODg1NDMxYTI4MjFhMDEzZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yhIRXzOE5FXW-OMB93lKLp-Z3ewolOEyWgSK56qIKL4)

You have to turn off Real Time Protection in order to open this exe file. Windows Defender flags most of the exe files as potential threat mostly when it contains any automated behavior. Thank you :D
